default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  host: localhost
  user: postgres
  pool: 5

development:
  <<: *default
  database: url_shortner_development
  password: postgres

production:
  <<: *default
  database: url_shortner_production
  password: postgres